### ISSUE TITLE
appid

### ISSUE THREAD

**Issue by chenkelvin** [modojs/wxapp-ui#10]
朋友，你的app ID 需要删一下么？

虽然，已经不存在服务器支持了。主要是看上去好像不安全的样子！～

Orz，我几乎把你的全部都扫了一边，主要是js！～

**Comment by Akiq2016** [comment]
谢谢关心～ 那个appid没事的～ 做开发浏览和后期的docs预览作用！
目前还在间歇性抽空开发中～

**Comment by chenkelvin** [comment]
嗯啊，我也是那天无意中搜索到的，也是好奇想看看代码，反正看看也可以开拓一下视野。
你加油啊！

Kelvin’s iPhone
